# Reload and Start Flask Service
- name: Reload systemd and start the Flask app service
  systemd:
    name: "{{ service_name }}"
    state: restarted
    enabled: true
    daemon_reload: yes

# Reload Nginx Service
- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: true


