---
- name: Server Setup
  hosts: localhost
  become: true
  vars_files: external_vars.yml
  tasks:
    - name: Install required packages
      apt:
        name:
          - sqlite3
          - nginx
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    # - name: Creates directory
    #   ansible.builtin.file:
    #   path: "{{ webapp_dir }}"
    #   state: directory

    # Create a Systemd Service for Flask App
    - name: Create a systemd service file
      copy:
        dest: "/etc/systemd/system/{{ service_name }}.service"
        content: |
          [Unit]
          Description=Flask App
          After=network.target

          [Service]
          User=root
          WorkingDirectory={{ webapp_dir }}
          ExecStart={{ webapp_dir }}/venv/bin/python {{ webapp_dir }}/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    # Reload and Start Flask Service
    - name: Reload systemd and start the Flask app service
      systemd:
        name: "{{ service_name }}"
        state: restarted
        enabled: true
        daemon_reload: yes

    # Configure Nginx as a Reverse Proxy
    - name: Create an Nginx configuration file
      copy:
        dest: "/etc/nginx/sites-available/{{ service_name }}"
        content: |
          server {
              listen 80;
              server_name flaskapp.local;

              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    # Enable Nginx Configuration
    - name: Enable Nginx site configuration
      file:
        src: "/etc/nginx/sites-available/{{ service_name }}"
        dest: "/etc/nginx/sites-enabled/{{ service_name }}"
        state: link

    # Remove default Nginx site
    - name: Remove the default Nginx configuration
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    # Restart Nginx
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: true