---
- name: Server Setup
  hosts: localhost
  become: true
  vars_files: external_vars.yml
  tasks:
    - name: Install required packages
      apt:
        name:
          - sqlite3
          - nginx
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Creates directory
      ansible.builtin.file:
      path: "{{ app_dir }}"
      state: directory

   


    - name: Enable and start Nginx
      service:
        name: nginx
        state: started
        enabled: true
