---
- name: Server Setup
  hosts: localhost
  become: true
  vars_files: external_vars.yml
  tasks:
    - name: Install required packages
      apt:
        name:
          - sqlite3
          - nginx
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Creates directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory

    - name: Creates directory
      ansible.builtin.file:
        path: "/var/log/uwsgi"
        state: directory
        mode: '0755'

    # Create a Systemd Service for Flask App
    - name: Create a systemd service file
      copy:
        dest: "/etc/systemd/system/{{ service_name }}.service"
        content: |
          [Unit]
          Description=Feed back Flask App
          After=network.target

          [Service]
          User=root
          WorkingDirectory={{ app_dir }}/webapp
          ExecStart={{ app_dir }}/webapp/venv/bin/uwsgi --ini {{ app_dir }}/webapp/uwsgi.ini
          Restart=always

          [Install]
          WantedBy=multi-user.target

    # Configure Nginx as a Reverse Proxy
    - name: Create an Nginx configuration file
      copy:
        dest: "/etc/nginx/sites-available/{{ service_name }}"
        content: |
          server {
              listen 80;
              server_name flaskapp.local;

              location / {
                  return 301 /feedback;
              }

              location /feedback {
                  include uwsgi_params;
                  uwsgi_pass unix:/opt/feedback_app/webapp/flask_app.sock;
              }
          }

    # Enable Nginx Configuration
    - name: Enable Nginx site configuration
      file:
        src: "/etc/nginx/sites-available/{{ service_name }}"
        dest: "/etc/nginx/sites-enabled/{{ service_name }}"
        state: link

    # Remove default Nginx site
    - name: Remove the default Nginx configuration
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent