---
- name: Task Updater Deployment
  hosts: localhost
  become: true
  vars_files:
    - asana.yml
    - external_vars.yml
  vars:
    asana_project_id: 1209273349038992
  tasks:

    - name: Install Perl and dependencies
      apt:
        name:
          - perl
          - libdbd-sqlite3-perl
          - libjson-perl
          - libwww-perl
        state: present

    - name: Install Perl Modules Using CPAN
      command: cpan --notest {{ item }}
      loop:
        - DBD::SQLite
        - JSON
        - LWP::UserAgent
      ignore_errors: yes

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ app_dir }}/task"
        state: directory
        mode: '0755'

    - name: Deploy feedback analyzer script
      template:
        src: ../feedback_analyzer/feedback_analyzer.pl.j2
        dest: "{{ app_dir }}/task/feedback_analyzer.pl"
        mode: '0755'

    - name: Set up a cron job to run script daily
      cron:
        name: "Run Feedback Analyzer"
        job: "/usr/bin/perl {{ app_dir }}/task/feedback_analyzer.pl"
        minute: "59"
        hour: "23"
        state: present
