---
- name: Web Application Deployment
  hosts: localhost
  become: true
  vars_files: external_vars.yml
  tasks:

    - import_tasks: git_tasks.yml

    - name: Deploy newest files
      command: cp -r "{{ temp_dir }}/webapp" "{{ app_dir }}"

     # Create a Python Virtual Environment
    - name: Create a virtual environment
      command: python3 -m venv "{{ app_dir }}/webapp/venv"
      args:
        creates: "{{ app_dir }}/webapp/venv"

     # Install Required Python Packages
    - name: Install Python dependencies
      command: "{{ app_dir }}/webapp/venv/bin/pip install -r {{ app_dir }}/webapp/requirements.txt"
      args:
        chdir: "{{ app_dir }}"
