---
- name: Web Application Deployment
  hosts: localhost
  become: true
  tasks:
    - ansible.builtin.import_tasks: git_clone.yml

    - name: Install Python dependencies
      pip:
        requirements: /opt/final_project/webapp/requirements.txt
